config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations]

  namespace :admin do
    root to: "admin/home#index"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController

def index
end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
before_action :authenticate_admin
    def authenticate_admin
        redirect_to new_admin_session_path unless current_admin?
    end

    def current_admin?
        if current_admin.present?
            true
        else
            false
        end

    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/home/index.html.erb
<h1>Teste da index admin</h1>

app/views/layouts/admin.html.erb
<% content_for :content do %>
  <%= render "layouts/admin/header" %>
  <div class="container mt-5">
    <%= yield %>
  </div>
<% end %>
<%= render template: "layouts/application" %>

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container">
    <ul class="navbar-nav">
      <li class="nav-item <%= current_page?(admin_root_path)? "active" : "" %>">
        <%= link_to("Home", admin_root_path, class: "nav-link") %>
     </li>
      <li class="nav-item <%= current_page?(admin_admins_path)? "active" : "" %>">
        <%= link_to("Administradores", admin_admins_path, class: "nav-link") %>
      </li>
      <li class="nav-item" <%= current_page?(admin_users_path)? "active" : "" %>">
        <%= link_to("Usuários", admin_users_path, class: "nav-link") %>
      </li>
      <li class="nav-item <%= current_page?(admin_posts_path)? "active" : "" %>">
        <%= link_to("Posts", admin_posts_path, class: "nav-link") %>
      </li>-->
    </ul>
    <div class="nav-item d-flex">
      <ul class="navbar-nav">
        <li class="nav-item">
          <div class="py-2 mr-4" style="color:#fff;"><%= current_admin.email %></div>
        </li>
        <li class="nav-item">
          <%= link_to("Sair", destroy_admin_session_path, method: :delete, class: "nav-link")%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html style= "heigth:100%;">
<html>
  <head>
    <title>SocialNetworking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <!--Dependencias do bootstrap-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
   <!---->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style= "heigth:100%;">
   <%= content_for?(:content) ? yield(:content): yield %>
  
  </body>
</html>